#DDPM
timesteps: 500
beta_schedule: "linear"
objective: "pred_noise"
betas: (1e-4, 0.02)

#General NN
epochs: 2
batch_size: 10
model_name: "ContextUnet"
cond_model: "mlp"
lr: 1e-3
save_rate: 2

#Data
seq_len: 15
num_customers: 4096

#Transformer
latent_dim: 256
num_layers: 6
n_heads: 8

#ContextUnet
img_rows: 64
img_cols: 64
channels: 1
n_feat: 64
