#DDPM
timesteps: 1000
beta_schedule: "linear"
objective: "pred_noise"
betas: (0.9, 0.99)

#General NN
epochs: 50
batch_size: 64
model_name: "TransEncoder"
cond_model: "te"
lr: 1e-4
save_rate: 10

#Data
seq_len: 15
subset_len: None

#Transformer
latent_dim: 256
num_layers: 6
n_heads: 8