#DDPM
timesteps: 1000
beta_schedule: "linear"
objective: "pred_noise"
betas: (0.9, 0.99)

#General NN
epochs: 4
batch_size: 64
model_name: "BaseLine"
cond_model: "mlp"
lr: 1e-4
save_rate: 2

#Data
seq_len: 15
subset_len: None
dataset: "HouseZero"
house_zero_feature_subset: ["NET", "Cooling", "PV_meter1_load (kW)", "PV_meter2_load (kW)", "Battery cabinet", "Sumppump", "Plug_Basement", "Solar rapid shutdown"]

#Transformer
latent_dim: 256
num_layers: 6
n_heads: 8