#DDPM
timesteps: 1000
beta_schedule: "cosine"
objective: "pred_noise"

#General NN
epochs: 2000
batch_size: 256
model_name: "TransEncoder"
cond_model: "mlp"
lr: 1e-4
save_rate: 100
betas: (0.9, 0.99)

#Data
seq_len: 12

#Transformer
latent_dim: 256
num_layers: 6
n_heads: 8
